spring:
  datasource:
    url: jdbc:h2:mem:local;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: true

my:
  jpa:
    query:
      logger:
        enabled: true
        local-query-threshold: 0
        global-query-measurement-time-ms: 10000
        global-query-invoke-count-threshold: 5
